no1=int(input("Enter First Number:"))
no2=int(input("Enter Second Number:"))
#print("Addition of "+str(no1)+" and "+str(no2)+" is :"+str(no1+no2))
#print("Addition is:",no1+no2)
print("Sum of {0} and {1} is {2}" .format(no1, no2, no1+no2))
print("Sub of {0} and {1} is {2}" .format(no1, no2, no1-no2))
print("Mul of {0} and {1} is {2}" .format(no1, no2, no1*no2))
print("Div of {0} and {1} is {2}" .format(no1, no2, no1/no2))
print("Mod of {0} and {1} is {2}" .format(no1, no2, no1%no2))
print("FloorDiv of {0} and {1} is {2}" .format(no1, no2, no1//no2))
